---
- name: Update ssh_keys in known_hosts file
  hosts: localhost
  tasks:
    - name: delete all old items in know_hosts file
      lineinfile:
        path: '~/.ssh/known_hosts'
        regexp: '{{ item }}'
        state: absent
      loop: "{{ groups.v2v_servers }}"

    - name: get remote host's ssh key
      command: 'ssh-keyscan -t ecdsa-sha2-nistp256 {{ item }}'
      register: ssh_keyscan_res
      loop: "{{ groups.v2v_servers }}"

    - name: update knowhosts file
      known_hosts:
        name: "{{ item.item }}"
        state: present
        key: "{{ item.stdout }}"
      loop: "{{ ssh_keyscan_res.results }}"

- name: setup automation develop envrionment
  hosts: v2v_servers
  vars:
    pkgs:
      - git
      - virt-v2v
      - vim
      - virtio-win
      - tcpdump
      - gcc
      - virt-install
      - libvirt
      - qemu-kvm
      - platform-python-devel
    pkgs_8: []
    pkgs_9: []
    pip_pkgs_9:
      - Pillow
    proxy_env:
      http_proxy: ''
      https_proxy: ''
    jobs_yaml: ''
  roles:
    - vtools_auto_env
  pre_tasks:
    - name: Wecome to use avtools_auto_env ansible script
      debug:
        msg: >
          Welcome!

  tasks:
    - import_tasks: vtools_auto_env/tasks/replace_variants.yml
      when: jobs_yaml is defined and jobs_yaml != ''
