---
# tasks file for vtools_auto_env
- name: prepare packages for v2v servers on rhel9 or newer
  set_fact:
    pkgs_all: "{{ pkgs + pkgs_9 }}"
  when: ansible_facts.distribution == "RedHat" and ansible_facts.distribution_major_version is version('9', '>=')

- name: prepare packages for v2v servers on rhel8
  set_fact:
    pkgs_all: "{{ pkgs + pkgs_8 }}"
  when: ansible_facts.distribution == "RedHat" and ansible_facts.distribution_major_version is version('8', '==')

- name: install packages in v2v server
  yum:
    name: '{{ pkgs_all }}'
    state: latest
    disable_gpg_check: yes
  notify: __restart_libvirtd

- name: "cloning source codes"
  git:
    repo: "{{ item.repo }}"
    dest: "{{ code_root_dir }}/{{ item.name }}"
    update: 'no'
    #force: 'yes'
  loop: '{{ projects }}'
  environment: "{{ proxy_env }}"

- name: 'installing avocado'
  command:
    cmd: "{{ ansible_facts['discovered_interpreter_python'] }} setup.py install"
    chdir: "{{ code_root_dir }}/avocado"
    creates: '/usr/local/bin/avocado'

- name: 'installing avocado-vt'
  command:
    cmd: "{{ ansible_facts['discovered_interpreter_python'] }} setup.py develop"
    chdir: "{{ code_root_dir }}/avocado-vt"
    creates: '/usr/local/lib/python3.6/site-packages/avocado-framework-plugin-vt.egg-link'

- name: 'setup tp-libvirt cases'
  lineinfile:
    path: "{{ code_root_dir }}/avocado-vt/virttest/test-providers.d/io-github-autotest-libvirt.ini"
    regexp: '^uri:'
    line: "uri: file://{{ code_root_dir | regex_replace('\\/$', '') }}/tp-libvirt"

- name: "running 'avocado vt-bootstrap'"
  command:
    cmd: "avocado vt-bootstrap --yes-to-all"
    creates: '/var/lib/avocado/data/avocado-vt/images/jeos-27-x86_64.qcow2.xz'
  environment: "{{ proxy_env }}"
  notify: __v2v_vt_bootstrap

